# Generated by Django 6.0.1 on 2026-01-20 02:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=255, verbose_name="Nombre del lugar"),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Descripción"),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("restaurant", "Restaurante"),
                            ("bar", "Bar / Pub"),
                            ("attraction", "Atracción Turística"),
                            ("other", "Otro"),
                        ],
                        default="other",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Borrador / Pendiente"),
                            ("approved", "Publicado / Aprobado"),
                            ("archived", "Archivado (No Visible)"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                ("city", models.CharField(default="Santiago", max_length=100)),
                ("address", models.CharField(blank=True, max_length=255)),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "image_url",
                    models.URLField(
                        blank=True,
                        help_text="URL de la imagen (Fase 11.5)",
                        max_length=500,
                    ),
                ),
                (
                    "pros",
                    models.TextField(
                        blank=True,
                        help_text="Lo mejor del lugar (separado por comas o saltos de línea)",
                    ),
                ),
                (
                    "cons",
                    models.TextField(blank=True, help_text="Lo que podría mejorar"),
                ),
                (
                    "vibe_match_score",
                    models.IntegerField(
                        default=70,
                        help_text="Porcentaje de afinidad calculado (0-100)",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Lugar",
                "verbose_name_plural": "Lugares",
                "ordering": ["-vibe_match_score", "name"],
            },
        ),
    ]
