# Generated by Django 6.0.1 on 2026-01-25 15:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("locations", "0002_mood_alter_location_options_remove_location_cons_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="collectible",
            options={
                "verbose_name": "Coleccionable",
                "verbose_name_plural": "Coleccionables",
            },
        ),
        migrations.AlterModelOptions(
            name="favorite",
            options={"verbose_name": "Favorito", "verbose_name_plural": "Favoritos"},
        ),
        migrations.AlterModelOptions(
            name="promotion",
            options={"verbose_name": "Promoción", "verbose_name_plural": "Promociones"},
        ),
        migrations.AlterModelOptions(
            name="visit",
            options={"verbose_name": "Visita", "verbose_name_plural": "Visitas"},
        ),
        migrations.AlterField(
            model_name="visit",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pendiente"),
                    ("active", "Activo"),
                    ("completed", "Completado"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="collectible",
            unique_together={("user", "location")},
        ),
        migrations.AlterUniqueTogether(
            name="favorite",
            unique_together={("user", "location")},
        ),
    ]
